### PR TITLE
Create superclass for map components

### PR DESCRIPTION
**Pull request by xkjyeah**
Hi! It's this PR again.

The notable changes are as follows:

1. A Vue plugin (`DeferredReady`) which creates a new hook called `deferredReady`, and a mixin called `DeferredReadyMixin`. `DeferredReadyMixin` is a general-purpose mixin intended for components that depend on certain resources from their parents, including resources that may require asynchronous loading (hence Promises). Classes that contain `DeferredReadyMixin` will fire `deferredReady` at some point after `ready`. If there are no ancestors containing `DeferredReadyMixin` then it will fire immediately after `ready`. Otherwise, classes will wait for ancestors' `deferredReady` to complete before firing. If `deferredReady` returns a `Promise`, then descendent components' `deferredReady` will only fire **after the promise resolves**.
2. A `MapComponent` class that contains `DeferredReadyMixin`. This class handles signalling between the map and its components. It guarantees that when `deferredReady` on a subclass is called, a new property `$map` has been created on the vm which points to the Google Maps object.

*Example:* the `Map` component is a top-level `DeferredReadyMixin`. `deferredReady` is fired immediately after `ready`. However, it returns a promise that waits for the Google Maps API to be fully loaded. Therefore, in the descendents *none* of the deferredReady are fired until the Google Maps API has been loaded, because they wait for the promise to be resolved.

Similarly, in the `Marker` class, `deferredReady` creates an instance of `google.maps.Marker`. If the marker has a descendent `InfoWindow`, the info window's `deferredReady` is called only after the Google API's Marker instance has been created; so the info window has no problem attaching itself to the marker.

This way, we can eliminate most signals in the component classes.

### CODE REVIEW

**Comment by GuillaumeLeclerc** [comment]
Looks good. Have you tested it on the `vue-google-maps` examples ?

**Comment by xkjyeah** [comment]
Yep

**Comment by GuillaumeLeclerc** [comment]
I took a deeper and it looks very cool ! I'll run tests myself and merge it if everything is fine

**Comment by GuillaumeLeclerc** [comment]
Sorry but when I checked out the master branch of your repo I get this error on `vue-google-maps-examples`

`Uncaught TypeError: e.map is not a function
http://localhost:8003/favicon.ico Failed to load resource: the server responded with a status of 404 (File not found)`

```javascript
s["default"].all(e.map(function(e) {
```

Did I missed somthing ?

**Comment by xkjyeah** [comment]
Hm. First, turn off minification. That looks like Promise.all trying to run
on Array.prototype.map, but the array is undefined. I'll have a look again.

**Comment by xkjyeah** [comment]
May I know what version of Vue is installed?

I had some problems with Vue 1.0.19. I tested mine with 1.0.17.

**Comment by GuillaumeLeclerc** [comment]
I tested it with 1.0.18. This is the latest version supported with `vue-google-maps`. I haven't had the time to test with 19 at the moment

**Comment by xkjyeah** [comment]
1.0.19 has a regression and breaks vue-google-maps. Try 1.0.20 instead. So,
did you mean that my PR did not work with 1.0.18?

**Comment by GuillaumeLeclerc** [comment]
This is what I meant yes your PR breaks for me with 1.0.18

**Comment by xkjyeah** [comment]
Are you symlinking vue-google-maps from -examples? Unfortunately this
breaks require() and includes Vue twice. The plugin is built with the Vue
from vue-google-maps but the maps components with the Vue from -examples.
Without the plugin the components break.

Under -examples, install vue-google-maps with npm, and then replace
index.js with the webpacked version from my PR.

**Comment by GuillaumeLeclerc** [comment]
what I do is `import ...  form '../../vue-google-maps/index.js'

I test all releases this way and it has always been working, except for this one so I doubt the problem comes from here. especially when there is an error at running time and not at compile time.

**Comment by xkjyeah** [comment]
Well I remember encountering the same problem when testing. TL;Dr try it
and you'll see whether it works.

Tl;dr2 : count the number of times the string "1.0.1" appears in build.js.
If it happens twice it's because there are two copies of Vue.

TL;dr3 : modify vue-google-maps to export DeferredReady plugin, and
Vue.use(DeferredReadyPlugin) in -examples.

TL;dr4 : copy index.js to the root folder of examples as vue-google-maps.js
and import it via import '../vue-google-maps'

The reason why there cannot be two instances of Vue is that the plugin adds
a property to Vue.config.optionMergeStrategies which tells Vue to merge
multiple deferredReady hooks into an array (ensuring that deferredReady.map
will be a function) Without this configuration, deferredReady in a Vue
instance would overwrite the one from its superclass. If deferredReady is a
function, deferredReady.map is undefined. Which is the error you are
getting.

If vue-google-maps is in node_modules, npm handles peer dependencies
correctly and uses the instance of Vue from -examples. If vue-google-maps
is a symlink or some other folder, any require() in it resolves to the copy
of Vue in its folder. That copy of Vue has the updated
mergeOptionStrategies but the Vue from -examples does not.

**Comment by GuillaumeLeclerc** [comment]
Ok I'll do this when I have time.

But if it works that means this PR: 

- Is not backward compatible. (All `vue-google-maps` user will have to to these changes to their code base). If it was backward compatible I could just use your version without changing my code nor the build process.
- Introduce complexity. `vue-google-maps` is more complex to setup.

If you could update your PR with a backward compatible one I would accept it. In the other case I think we need the opinion of other users to see if they are willing to change their code-base for this PR.

**Comment by GuillaumeLeclerc** [comment]
Copying inside node_modules worked. I'm sorry I did'nt understood what you said.

I'm merging it

**Comment by xkjyeah** [comment]
No problem. You're right that it complicates testing. I had to write a
Makefile that copies index.js over to the
-examples/node_modules/vue-google-maps directory, for example. I'm not sure
how to design a better solution.

**Comment by GuillaumeLeclerc** [comment]
I don't care if it's more complex for a tester, as soon as a user can just npm-install it
